### ISSUE TITLE
Does not work with serverless-http module

### ISSUE THREAD

**Issue by AndrewBarba** [thundra-io/thundra-lambda-agent-nodejs#8]
I have a really simple proxy handler setup with `serverless-http` that is not working with Thundra. No requests are completing, and looking at the logs the lambda seems to be constantly restarting. I had this exact setup with IOPipe and it works fine.

Environment: Node.js 8.10

Handler:
```javascript
const http = require('serverless-http')
const { server } = require('app/')
const thundra = require("@thundra/core")()
const proxy = http(server.router, { callbackWaitsForEmptyEventLoop: false })

exports.handler = thundra(proxy)
```

**Comment by morellic** [comment]
Hey @AndrewBarba ,
I could not reproduce this, Thundra is working with the following setup on both Node.js 8.10 and 6.10 runtimes:

Handler:
```js
const thundra = require('@thundra/core')();
const http = require('serverless-http');
const express = require('express');
const app = express();
const proxy = http(app, { callbackWaitsForEmptyEventLoop: false });

app.get('/', (req, res) => {
    res.json({ success: true , msg: "Hello"});
});

exports.handler = thundra(proxy);
```

Serverless.yml:
```yml
service: httpsls

custom:
  deploymentBucket: my-dev-bucket #TODO: enter your AWS S3 deployment bucket here
  thundraApiKey: my-api-key #TODO: enter your API key here
  stage: dev
  region: us-west-2
  profile: default
  skipLogGroupCreation: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  profile: ${self:custom.profile}
  deploymentBucket: ${self:custom.deploymentBucket}
  memorySize: 256
  timeout: 10
  environment:
      thundra_apiKey: ${self:custom.thundraApiKey}
      thundra_lambda_publish_cloudwatch_enable: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:*
      Resource: [
        "*"
      ]

plugins:
  - serverless-plugin-thundra-monitor-cw

functions:
  httpsls:
    handler: index.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{path+}
          method: ANY
          cors: true
```

I would appreciate if you could give more details such as:
* does your lambda timeout
* can you determine at which point of execution the function fails
* any error logs that you can share
* would your lambda fail again if you set `thundra_disable` environment variable true (similarly `thundra_disable_trace` or `thundra_disable_metric`)
* are you using express or something else
